### ISSUE TITLE
Transfering

### ISSUE THREAD

**Issue by grendizerh** [Pymmdrza/SoloMiner#4]
Does the program transfer the bitcoin to the address?

**Comment by Pymmdrza** [comment]
> Does the program transfer the bitcoin to the address?

```python
inpAdd = input('[*] INSERT HERE YOUR ADDRESS BITCOIN WALLET For Withdrawal : ')
address = str(inpAdd)
print(Fore.YELLOW,'\nBitcoin Wallet Address ===>> ',Fore.GREEN,str(address))
```
link to line[ `75` ](https://github.com/Pymmdrza/SoloMiner/blob/08547ea7dd047b7bde2ac530faa76931e8e8424e/SoloMiner.py#L75)file for input address bitcoin wallet : [#75](https://github.com/Pymmdrza/SoloMiner/blob/08547ea7dd047b7bde2ac530faa76931e8e8424e/SoloMiner.py#L75)
